import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Sidebar from '../components/Sidebar';
import { BookOpen, ChevronDown, Zap, CheckCircle, AlertCircle, Lightbulb, Brain, Settings, Layers, BarChart3, ClipboardList } from 'lucide-react';
import KnowledgeSetupModal from '../components/KnowledgeSetupModal';
import { generateNotesFromHuggingFace } from '../utils/huggingfaceApi';
import { getTopicsForSubject } from '../data/masteryTopics';



export default function Knowledge() {
  const [activeSection, setActiveSection] = useState('practice');
  const [userSetup, setUserSetup] = useState(null);
  const [showSetupModal, setShowSetupModal] = useState(false);
  const [selectedTopic, setSelectedTopic] = useState(null);
  const [selectedTopics, setSelectedTopics] = useState([]);
  const [notes, setNotes] = useState(null);
  const [practiceQuestions, setPracticeQuestions] = useState(null);
  const [loading, setLoading] = useState(false);
  const [subjects, setSubjects] = useState([]);
  const [quizQuestions, setQuizQuestions] = useState([]);
  const [quizLoading, setQuizLoading] = useState(false);
  const [quizError, setQuizError] = useState(null);
  const [currentQuizIndex, setCurrentQuizIndex] = useState(0);
  const [quizSelectedAnswer, setQuizSelectedAnswer] = useState(null);
  const [quizAnswered, setQuizAnswered] = useState(false);
  const [quizStats, setQuizStats] = useState({
    attempted: 0,
    correct: 0,
    wrong: 0,
  });

  useEffect(() => {
    const savedSubjects = localStorage.getItem('subjects');
    if (savedSubjects) {
      setSubjects(JSON.parse(savedSubjects));
    }

    const savedSetup = localStorage.getItem('knowledgeSetup');
    if (savedSetup) {
      setUserSetup(JSON.parse(savedSetup));
    }

    const savedQuizStats = localStorage.getItem('quickQuizStats');
    if (savedQuizStats) {
      try {
        setQuizStats(JSON.parse(savedQuizStats));
      } catch {
        // ignore parse errors and start fresh
      }
    }
  }, []);

  // Persist quiz stats so they "exist somewhere" beyond this session
  useEffect(() => {
    try {
      localStorage.setItem('quickQuizStats', JSON.stringify(quizStats));
    } catch {
      // ignore storage errors
    }
  }, [quizStats]);

  const handleSetupComplete = (setup) => {
    setUserSetup(setup);
    localStorage.setItem('knowledgeSetup', JSON.stringify(setup));
    setShowSetupModal(false);
    setSelectedTopics([]);
  };

  const handleTopicToggle = (topicId) => {
    setSelectedTopics(prev => {
      if (prev.includes(topicId)) {
        return prev.filter(id => id !== topicId);
      } else {
        return [...prev, topicId];
      }
    });
  };

  const generateNotes = async (topic) => {
    if (!userSetup) return;

    setLoading(true);

    try {
      // Generate notes using AI API with web search
      const generatedNotes = await generateNotesFromHuggingFace(
        topic,
        userSetup.qualification,
        userSetup.subject,
        userSetup.examBoard
      );

      setPracticeQuestions(generatedNotes);
    } catch (error) {
      console.error('Error generating questions:', error);
      setNotes({
        title: topic,
        summary: error.message || 'Unable to generate notes at the moment. Please try again.',
        mainPoints: [],
        keyTerms: [],
        practiceQuestions: []
      });
      setPracticeQuestions([]);
    } finally {
      setLoading(false);
    }
  };

  const getTopicsForDisplay = () => {
    if (!userSetup || !userSetup.topics) return [];

    // Use topics from the setup (generated by AI)
    return Array.isArray(userSetup.topics) ? userSetup.topics : [];
  };

  const handleTopicChange = (topic) => {
    setSelectedTopic(topic);
    setNotes(null);
    setPracticeQuestions(null);
    generateNotes(topic);
  };

  const getSelectedTopicNames = () => {
    if (!userSetup) return [];
    const allTopics = getTopicsForSubject(
      userSetup.qualification,
      userSetup.examBoard,
      userSetup.subject
    );
    return allTopics
      .filter((topic) => selectedTopics.includes(topic.id))
      .map((topic) => topic.name);
  };

  const createFallbackQuickQuizQuestions = (topicNames, setup) => {
    // Don't create fallback questions - we should always try to get real questions from AI
    // If we truly can't, return empty array and show an error
    return [];
  };

  const startQuickQuiz = async () => {
    if (!userSetup) return;
    let topicNames = getSelectedTopicNames();
    // If no topics have been selected, fall back to the first few syllabus topics
    if (topicNames.length === 0) {
      try {
        const allTopics = getTopicsForSubject(
          userSetup.qualification,
          userSetup.examBoard,
          userSetup.subject
        );
        topicNames = (allTopics || []).slice(0, 3).map((t) => t.name);
      } catch {
        topicNames = [];
      }
    }

    if (topicNames.length === 0) {
      setQuizError('Please select at least one topic to generate quiz questions.');
      setActiveSection('quiz');
      return;
    }

    setActiveSection('quiz');
    setQuizLoading(true);
    setQuizError(null);
    setQuizQuestions([]);
    setCurrentQuizIndex(0);
    setQuizSelectedAnswer(null);
    setQuizAnswered(false);

    try {
      // Generate questions for EACH topic individually to get real content questions
      const allQuestions = [];
      
      // Process topics one by one to get better quality questions
      for (const topicName of topicNames.slice(0, 5)) { // Limit to 5 topics max
        try {
          const generatedNotes = await generateNotesFromHuggingFace(
            topicName,
            userSetup.qualification,
            userSetup.subject,
            userSetup.examBoard
          );

          const questions = (generatedNotes || []).filter(
            (q) => 
              q && 
              q.question && 
              q.question.trim().length > 0 &&
              Array.isArray(q.options) && 
              q.options.length >= 2 &&
              q.correctAnswer &&
              q.explanation
          );

          // Only add questions that are actually about the topic (not generic)
          const validQuestions = questions.filter(q => {
            const questionText = q.question.toLowerCase();
            const topicLower = topicName.toLowerCase();
            // Check if question mentions the topic or seems topic-specific
            return questionText.includes(topicLower) || 
                   questionText.length > 30; // Real questions are usually longer
          });

          allQuestions.push(...validQuestions);
        } catch (topicError) {
          console.error(`Error generating questions for topic ${topicName}:`, topicError);
          // Continue with other topics
        }
      }

      // If we got questions, use them
      if (allQuestions.length > 0) {
        // Shuffle and limit to 8-10 questions for a quick quiz
        const shuffled = allQuestions.sort(() => Math.random() - 0.5);
        setQuizQuestions(shuffled.slice(0, 10));
      } else {
        // If no questions were generated, try one more time with all topics combined
        try {
          const combinedTopic = topicNames.join(', ');
          const generatedNotes = await generateNotesFromHuggingFace(
            combinedTopic,
            userSetup.qualification,
            userSetup.subject,
            userSetup.examBoard
          );

          const questions = (generatedNotes || []).filter(
            (q) => 
              q && 
              q.question && 
              q.question.trim().length > 0 &&
              Array.isArray(q.options) && 
              q.options.length >= 2 &&
              q.correctAnswer &&
              q.explanation
          );

          if (questions.length > 0) {
            setQuizQuestions(questions.slice(0, 10));
          } else {
            setQuizError('Unable to generate quiz questions. Please check your API configuration or try selecting different topics.');
          }
        } catch (finalError) {
          console.error('Error in final question generation attempt:', finalError);
          setQuizError('Unable to generate quiz questions. Please check your API configuration or try again later.');
        }
      }
    } catch (error) {
      console.error('Error starting quick quiz:', error);
      setQuizError('Failed to generate quiz. Please try again or check your API configuration.');
    } finally {
      setQuizLoading(false);
    }
  };

  const handleQuizAnswer = (option) => {
    if (!quizQuestions[currentQuizIndex] || quizAnswered) return;

    const currentQuestion = quizQuestions[currentQuizIndex];
    const isCorrect = option === currentQuestion.correctAnswer;

    setQuizSelectedAnswer(option);
    setQuizAnswered(true);
    setQuizStats((prev) => ({
      attempted: prev.attempted + 1,
      correct: prev.correct + (isCorrect ? 1 : 0),
      wrong: prev.wrong + (isCorrect ? 0 : 1),
    }));
  };

  const goToNextQuizQuestion = () => {
    if (currentQuizIndex + 1 < quizQuestions.length) {
      setCurrentQuizIndex((prev) => prev + 1);
      setQuizSelectedAnswer(null);
      setQuizAnswered(false);
    } else {
      // End of quiz - keep results visible and reset current question selection
      setQuizSelectedAnswer(null);
      setQuizAnswered(false);
    }
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { y: 30, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: {
        duration: 0.6,
        ease: "easeOut"
      }
    }
  };

  return (
    <div className="min-h-screen mt-20 flex bg-gradient-to-br from-slate-950 via-purple-950 to-slate-900">
      <Sidebar />
      
      {showSetupModal && (
        <KnowledgeSetupModal 
          subjects={subjects}
          onComplete={handleSetupComplete}
          onClose={() => setShowSetupModal(false)}
        />
      )}

      <div className="flex-1 ml-16 transition-all duration-300 ease-in-out [body>div>aside:hover_+_div&]:ml-64">
        <div className="max-w-7xl mx-auto p-6">
          {/* Header */}
          <motion.div
            className="mb-8"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div>
              <h1 className="text-5xl font-bold bg-gradient-to-r from-purple-400 via-pink-400 to-purple-600 bg-clip-text text-transparent mb-4">Mastery</h1>
              <p className="text-purple-200/80 text-lg">AI-powered flashcards, quizzes and mock exams</p>
            </div>
          </motion.div>

          {/* Setup Info or Setup Prompt */}
          {!userSetup ? (
            subjects.length === 0 ? (
              // No subjects - show link to subjects page
              <motion.div
                className="bg-gradient-to-br from-purple-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-purple-700/30 mb-8 text-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                <BookOpen className="w-12 h-12 text-purple-400 mx-auto mb-4" />
                <p className="text-white text-lg font-semibold mb-2">No Subjects Found</p>
                <p className="text-purple-200/80 mb-6">Create subjects first to use the Knowledge Base. Head to the Subjects page to get started.</p>
                <Link
                  to="/subjects"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-purple-500/50 transition-all transform hover:scale-105"
                >
                  <BookOpen className="w-4 h-4" />
                  Go to Subjects
                </Link>
              </motion.div>
            ) : (
              // Has subjects - show setup button
              <motion.div
                className="bg-gradient-to-br from-purple-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-purple-700/30 mb-8 text-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                <Settings className="w-12 h-12 text-purple-400 mx-auto mb-4" />
                <p className="text-white text-lg font-semibold mb-2">Get Started with Knowledge Base</p>
                <p className="text-purple-200/80 mb-6">Configure your qualification and subject to begin accessing AI-generated study notes and practice questions tailored just for you.</p>
                <motion.button
                  onClick={() => setShowSetupModal(true)}
                  className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-purple-500/50 transition-all transform hover:scale-105"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  <Settings className="w-4 h-4" />
                  Configure Now
                </motion.button>
              </motion.div>
            )
          ) : (
            // Setup exists - show setup info
            <motion.div
              className="bg-gradient-to-br from-purple-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-6 border border-purple-700/30 mb-8"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div className="space-y-2">
                  <p className="text-purple-300 text-sm">Study Program</p>
                  <p className="text-white text-lg font-semibold">
                    {userSetup.qualification} - {userSetup.subject} ({userSetup.examBoard})
                  </p>
                </div>
                <motion.button
                  onClick={() => setShowSetupModal(true)}
                  className="px-4 py-2 text-sm text-purple-300 border border-purple-500/50 rounded-lg hover:bg-purple-600/20 transition"
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                >
                  Change
                </motion.button>
              </div>
            </motion.div>
          )}

          {userSetup && (
            <>

              {/* Topic Selector with Checkboxes */}
              <motion.div
                className="mb-12"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.3 }}
              >
                <h2 className="text-white text-xl font-bold mb-4">Select Topics to Study</h2>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  {getTopicsForSubject(userSetup.qualification, userSetup.examBoard, userSetup.subject).map((topic) => (
                    <motion.button
                      key={topic.id}
                      onClick={() => handleTopicToggle(topic.id)}
                      className={`p-4 rounded-lg border-2 text-left transition-all ${
                        selectedTopics.includes(topic.id)
                          ? 'bg-gradient-to-br from-purple-600 to-pink-600 border-purple-400 text-white shadow-lg shadow-purple-500/50'
                          : 'bg-purple-900/30 border-purple-700/50 text-purple-200 hover:border-purple-600 hover:bg-purple-900/50'
                      }`}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                    >
                      <div className="flex items-start gap-3">
                        <div className={`w-5 h-5 rounded border-2 mt-1 flex items-center justify-center flex-shrink-0 transition ${
                          selectedTopics.includes(topic.id)
                            ? 'bg-white border-white'
                            : 'border-purple-400'
                        }`}>
                          {selectedTopics.includes(topic.id) && (
                            <CheckCircle className="w-4 h-4 text-purple-600" />
                          )}
                        </div>
                        <span className="font-medium text-sm">{topic.name}</span>
                      </div>
                    </motion.button>
                  ))}
                </div>
              </motion.div>

              {/* Three Mode Overview Cards */}
              {selectedTopics.length > 0 && (
                <motion.div
                  className="mb-12"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.4 }}
                >
                  <h2 className="text-white text-xl font-bold mb-6">Study Modes</h2>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {/* Flashcard Mode */}
                    <motion.div
                      className="bg-gradient-to-br from-cyan-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-8 border border-cyan-700/30 hover:border-cyan-600/50 transition-all cursor-pointer group"
                      whileHover={{ y: -5, scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <div className="flex items-start gap-4 mb-4">
                        <div className="p-3 bg-cyan-600/30 rounded-lg group-hover:bg-cyan-600/50 transition">
                          <Layers className="w-6 h-6 text-cyan-400" />
                        </div>
                        <div>
                          <h3 className="text-xl font-bold text-white">Flashcards</h3>
                          <p className="text-cyan-300/70 text-sm mt-1">Interactive learning</p>
                        </div>
                      </div>
                      <p className="text-cyan-200/80 text-sm leading-relaxed mb-6">
                        Master topics with spaced repetition. Review key concepts through digital flashcards designed for active recall and long-term retention.
                      </p>
                      <motion.button
                        className="w-full py-3 bg-gradient-to-r from-cyan-600 to-blue-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-cyan-500/50 transition-all"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Start Flashcards
                      </motion.button>
                      <p className="text-cyan-400/60 text-xs mt-3 text-center">
                        {selectedTopics.length} topic{selectedTopics.length !== 1 ? 's' : ''} selected
                      </p>
                    </motion.div>

                    {/* Quick Quiz Mode */}
                    <motion.div
                      className="bg-gradient-to-br from-amber-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-8 border border-amber-700/30 hover:border-amber-600/50 transition-all cursor-pointer group"
                      whileHover={{ y: -5, scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <div className="flex items-start gap-4 mb-4">
                        <div className="p-3 bg-amber-600/30 rounded-lg group-hover:bg-amber-600/50 transition">
                          <BarChart3 className="w-6 h-6 text-amber-400" />
                        </div>
                        <div>
                          <h3 className="text-xl font-bold text-white">Quick Quiz</h3>
                          <p className="text-amber-300/70 text-sm mt-1">Quick assessments</p>
                        </div>
                      </div>
                      <p className="text-amber-200/80 text-sm leading-relaxed mb-6">
                        Test your knowledge with quick quizzes. Get instant feedback on your answers and identify areas that need more study.
                      </p>
                      <motion.button
                        onClick={startQuickQuiz}
                        className="w-full py-3 bg-gradient-to-r from-amber-600 to-orange-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-amber-500/50 transition-all"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Start Quiz
                      </motion.button>
                      <p className="text-amber-400/60 text-xs mt-3 text-center">
                        {selectedTopics.length} topic{selectedTopics.length !== 1 ? 's' : ''} selected
                      </p>
                    </motion.div>

                    {/* Mock Exam Mode */}
                    <motion.div
                      className="bg-gradient-to-br from-pink-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-8 border border-pink-700/30 hover:border-pink-600/50 transition-all cursor-pointer group"
                      whileHover={{ y: -5, scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <div className="flex items-start gap-4 mb-4">
                        <div className="p-3 bg-pink-600/30 rounded-lg group-hover:bg-pink-600/50 transition">
                          <ClipboardList className="w-6 h-6 text-pink-400" />
                        </div>
                        <div>
                          <h3 className="text-xl font-bold text-white">Mock Exam</h3>
                          <p className="text-pink-300/70 text-sm mt-1">Full simulations</p>
                        </div>
                      </div>
                      <p className="text-pink-200/80 text-sm leading-relaxed mb-6">
                        Experience realistic exam conditions. Complete full-length practice papers with timed questions to build exam confidence.
                      </p>
                      <motion.button
                        className="w-full py-3 bg-gradient-to-r from-pink-600 to-rose-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-pink-500/50 transition-all"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Start Mock Exam
                      </motion.button>
                      <p className="text-pink-400/60 text-xs mt-3 text-center">
                        {selectedTopics.length} topic{selectedTopics.length !== 1 ? 's' : ''} selected
                      </p>
                    </motion.div>
                  </div>
                </motion.div>
              )}


              {/* Practice Section */}
              {activeSection === 'practice' && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.5 }}
                >
                  {loading ? (
                    <motion.div
                      className="bg-gradient-to-br from-blue-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-blue-700/30 flex flex-col items-center justify-center"
                      animate={{ scale: [0.95, 1.05, 0.95] }}
                      transition={{ duration: 2, repeat: Infinity }}
                    >
                      <Zap className="w-12 h-12 text-blue-400 mb-4" />
                      <p className="text-white text-lg font-semibold">Generating practice questions...</p>
                    </motion.div>
                  ) : practiceQuestions && practiceQuestions.length > 0 ? (
                    <motion.div
                      className="space-y-6"
                      variants={containerVariants}
                      initial="hidden"
                      animate="visible"
                    >
                      <motion.div
                        className="bg-gradient-to-br from-blue-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-8 border border-blue-700/30"
                        variants={itemVariants}
                      >
                        <h2 className="text-3xl font-bold text-white mb-2">Practice Questions</h2>
                        <p className="text-blue-200/80">Test your knowledge with these practice questions for {selectedTopic}</p>
                      </motion.div>

                      {practiceQuestions.map((question, index) => (
                        <PracticeQuestion
                          key={index}
                          question={question}
                          questionNumber={index + 1}
                          variants={itemVariants}
                        />
                      ))}
                    </motion.div>
                  ) : selectedTopic ? (
                    <motion.div
                      className="bg-gradient-to-br from-blue-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-blue-700/30 text-center"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                    >
                      <AlertCircle className="w-12 h-12 text-blue-400 mx-auto mb-4" />
                      <p className="text-white text-lg font-semibold">No practice questions available</p>
                      <p className="text-blue-200/80 text-sm mt-2">Please generate notes first to see practice questions</p>
                    </motion.div>
                  ) : (
                    <motion.div
                      className="bg-gradient-to-br from-blue-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-blue-700/30 text-center"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                    >
                      <Brain className="w-12 h-12 text-blue-400 mx-auto mb-4" />
                      <p className="text-white text-lg font-semibold">No practice content yet</p>
                      <p className="text-blue-200/80 text-sm mt-2">Select a topic and view notes to access practice questions</p>
                    </motion.div>
                  )}
                </motion.div>
              )}

              {/* Quick Quiz Section */}
              {activeSection === 'quiz' && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.5 }}
                >
                  {quizLoading ? (
                    <motion.div
                      className="bg-gradient-to-br from-amber-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-amber-700/30 flex flex-col items-center justify-center"
                      animate={{ scale: [0.95, 1.05, 0.95] }}
                      transition={{ duration: 2, repeat: Infinity }}
                    >
                      <BarChart3 className="w-12 h-12 text-amber-400 mb-4" />
                      <p className="text-white text-lg font-semibold">Generating your quick quiz...</p>
                    </motion.div>
                  ) : quizError ? (
                    <motion.div
                      className="bg-gradient-to-br from-red-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-red-700/30 text-center"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                    >
                      <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
                      <p className="text-white text-lg font-semibold mb-2">Quick quiz unavailable</p>
                      <p className="text-red-200/80 text-sm mb-6">{quizError}</p>
                      <motion.button
                        onClick={startQuickQuiz}
                        className="px-6 py-3 bg-gradient-to-r from-amber-600 to-orange-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-amber-500/50 transition-all"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Try Again
                      </motion.button>
                    </motion.div>
                  ) : quizQuestions.length === 0 ? (
                    <motion.div
                      className="bg-gradient-to-br from-amber-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-12 border border-amber-700/30 text-center"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                    >
                      <BarChart3 className="w-12 h-12 text-amber-400 mx-auto mb-4" />
                      <p className="text-white text-lg font-semibold">No quiz generated yet</p>
                      <p className="text-amber-200/80 text-sm mt-2 mb-6">
                        Select one or more topics and click &quot;Start Quiz&quot; to generate AI-powered questions.
                      </p>
                      <motion.button
                        onClick={startQuickQuiz}
                        className="px-6 py-3 bg-gradient-to-r from-amber-600 to-orange-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-amber-500/50 transition-all"
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                      >
                        Start Quiz
                      </motion.button>
                    </motion.div>
                  ) : (
                    <motion.div
                      className="space-y-6"
                      variants={containerVariants}
                      initial="hidden"
                      animate="visible"
                    >
                      <motion.div
                        className="bg-gradient-to-br from-amber-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-8 border border-amber-700/30"
                        variants={itemVariants}
                      >
                        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                          <div>
                            <h2 className="text-3xl font-bold text-white mb-1">Quick Quiz</h2>
                            <p className="text-amber-200/80 text-sm">
                              Question {Math.min(currentQuizIndex + 1, quizQuestions.length)} of {quizQuestions.length}
                            </p>
                          </div>
                          <div className="flex flex-wrap gap-4 text-sm">
                            <div className="px-3 py-2 rounded-lg bg-emerald-900/40 border border-emerald-600/40 text-emerald-200">
                              Correct: <span className="font-semibold">{quizStats.correct}</span>
                            </div>
                            <div className="px-3 py-2 rounded-lg bg-red-900/40 border border-red-600/40 text-red-200">
                              Wrong: <span className="font-semibold">{quizStats.wrong}</span>
                            </div>
                            <div className="px-3 py-2 rounded-lg bg-slate-900/60 border border-slate-600/40 text-slate-200">
                              Attempted: <span className="font-semibold">{quizStats.attempted}</span>
                            </div>
                          </div>
                        </div>
                      </motion.div>

                      {currentQuizIndex < quizQuestions.length ? (
                        <QuickQuizQuestion
                          question={quizQuestions[currentQuizIndex]}
                          questionNumber={currentQuizIndex + 1}
                          totalQuestions={quizQuestions.length}
                          variants={itemVariants}
                          selectedAnswer={quizSelectedAnswer}
                          answered={quizAnswered}
                          onAnswer={handleQuizAnswer}
                          onNext={goToNextQuizQuestion}
                        />
                      ) : (
                        <motion.div
                          className="bg-gradient-to-br from-emerald-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-10 border border-emerald-700/40 text-center"
                          variants={itemVariants}
                        >
                          <CheckCircle className="w-12 h-12 text-emerald-400 mx-auto mb-4" />
                          <p className="text-white text-xl font-semibold mb-2">Quiz complete!</p>
                          <p className="text-emerald-200/80 text-sm mb-6">
                            You answered {quizStats.correct} out of {quizStats.attempted} questions correctly.
                          </p>
                          <div className="flex justify-center gap-4">
                            <motion.button
                              onClick={startQuickQuiz}
                              className="px-6 py-3 bg-gradient-to-r from-amber-600 to-orange-600 text-white rounded-lg font-semibold hover:shadow-lg hover:shadow-amber-500/50 transition-all"
                              whileHover={{ scale: 1.05 }}
                              whileTap={{ scale: 0.95 }}
                            >
                              New Quiz
                            </motion.button>
                          </div>
                        </motion.div>
                      )}
                    </motion.div>
                  )}
                </motion.div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function PracticeQuestion({ question, questionNumber, variants }) {
  const [selectedAnswer, setSelectedAnswer] = useState(null);
  const [answered, setAnswered] = useState(false);

  const handleAnswer = (answer) => {
    setSelectedAnswer(answer);
    setAnswered(true);
  };

  const isCorrect = selectedAnswer === question.correctAnswer;

  return (
    <motion.div
      className="bg-gradient-to-br from-blue-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-6 border border-blue-700/30 hover:border-blue-600/50 transition-all"
      variants={variants}
      whileHover={{ y: -5 }}
      initial={{ opacity: 0, x: -20 }}
      whileInView={{ opacity: 1, x: 0 }}
      viewport={{ once: true }}
    >
      <div className="flex items-start gap-4 mb-4">
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-r from-blue-600 to-purple-600 flex items-center justify-center text-white font-bold text-sm">
          {questionNumber}
        </div>
        <h3 className="text-white text-lg font-semibold flex-1">{question.question}</h3>
      </div>

      <div className="space-y-3 mb-6">
        {question.options && question.options.map((option, index) => (
          <motion.button
            key={index}
            onClick={() => !answered && handleAnswer(option)}
            className={`w-full text-left px-4 py-3 rounded-lg border transition ${
              selectedAnswer === option
                ? isCorrect
                  ? 'bg-green-800/40 border-green-600/50 text-green-200'
                  : 'bg-red-800/40 border-red-600/50 text-red-200'
                : answered && option === question.correctAnswer
                  ? 'bg-green-800/40 border-green-600/50 text-green-200'
                  : 'bg-blue-800/20 border-blue-700/30 text-blue-200 hover:bg-blue-800/40'
            }`}
            whileHover={!answered ? { scale: 1.02 } : {}}
            whileTap={!answered ? { scale: 0.98 } : {}}
          >
            <div className="flex items-center gap-3">
              <div className="w-4 h-4 rounded border border-current" />
              <span>{option}</span>
            </div>
          </motion.button>
        ))}
      </div>

      {answered && (
        <motion.div
          className={`p-4 rounded-lg border ${
            isCorrect
              ? 'bg-green-800/20 border-green-600/30'
              : 'bg-red-800/20 border-red-600/30'
          }`}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-2 mb-2">
            {isCorrect ? (
              <>
                <CheckCircle className="w-5 h-5 text-green-400" />
                <p className="text-green-200 font-semibold">Correct!</p>
              </>
            ) : (
              <>
                <AlertCircle className="w-5 h-5 text-red-400" />
                <p className="text-red-200 font-semibold">Incorrect</p>
              </>
            )}
          </div>
          <p className="text-gray-300 text-sm">{question.explanation}</p>
        </motion.div>
      )}
    </motion.div>
  );
}

function QuickQuizQuestion({
  question,
  questionNumber,
  totalQuestions,
  variants,
  selectedAnswer,
  answered,
  onAnswer,
  onNext,
}) {
  const isCorrect = selectedAnswer === question.correctAnswer;

  return (
    <motion.div
      className="bg-gradient-to-br from-amber-900/40 to-slate-900/40 backdrop-blur-md rounded-2xl p-6 border border-amber-700/30 hover:border-amber-600/50 transition-all"
      variants={variants}
      whileHover={{ y: -5 }}
      initial={{ opacity: 0, x: -20 }}
      whileInView={{ opacity: 1, x: 0 }}
      viewport={{ once: true }}
    >
      <div className="flex items-start gap-4 mb-4">
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-r from-amber-500 to-orange-500 flex items-center justify-center text-white font-bold text-sm">
          {questionNumber}
        </div>
        <h3 className="text-white text-lg font-semibold flex-1">{question.question}</h3>
      </div>

      <div className="space-y-3 mb-6">
        {question.options &&
          question.options.map((option, index) => (
            <motion.button
              key={index}
              onClick={() => !answered && onAnswer(option)}
              className={`w-full text-left px-4 py-3 rounded-lg border transition ${
                selectedAnswer === option
                  ? isCorrect
                    ? 'bg-green-800/40 border-green-600/50 text-green-200'
                    : 'bg-red-800/40 border-red-600/50 text-red-200'
                  : answered && option === question.correctAnswer
                    ? 'bg-green-800/40 border-green-600/50 text-green-200'
                    : 'bg-amber-800/20 border-amber-700/30 text-amber-100 hover:bg-amber-800/40'
              }`}
              whileHover={!answered ? { scale: 1.02 } : {}}
              whileTap={!answered ? { scale: 0.98 } : {}}
            >
              <div className="flex items-center gap-3">
                <div className="w-4 h-4 rounded border border-current" />
                <span>{option}</span>
              </div>
            </motion.button>
          ))}
      </div>

      {answered && (
        <motion.div
          className={`p-4 rounded-lg border mb-4 ${
            isCorrect
              ? 'bg-green-800/20 border-green-600/30'
              : 'bg-red-800/20 border-red-600/30'
          }`}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-2 mb-2">
            {isCorrect ? (
              <>
                <CheckCircle className="w-5 h-5 text-green-400" />
                <p className="text-green-200 font-semibold">Correct!</p>
              </>
            ) : (
              <>
                <AlertCircle className="w-5 h-5 text-red-400" />
                <p className="text-red-200 font-semibold">Incorrect</p>
              </>
            )}
          </div>
          <p className="text-gray-300 text-sm">{question.explanation}</p>
        </motion.div>
      )}

      <div className="flex justify-between items-center mt-6 pt-4 border-t border-amber-700/30">
        <p className="text-amber-200/80 text-sm">
          Question {questionNumber} of {totalQuestions}
        </p>
        <motion.button
          onClick={onNext}
          disabled={!answered}
          className="px-6 py-3 rounded-lg bg-gradient-to-r from-amber-600 to-orange-600 text-white font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-lg hover:shadow-amber-500/50 transition-all flex items-center gap-2"
          whileHover={answered ? { scale: 1.05 } : {}}
          whileTap={answered ? { scale: 0.95 } : {}}
        >
          {questionNumber === totalQuestions ? (
            <>
              <CheckCircle className="w-4 h-4" />
              Finish Quiz
            </>
          ) : (
            <>
              Next Question
              <span className="text-lg">→</span>
            </>
          )}
        </motion.button>
      </div>
    </motion.div>
  );
}
